services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${DATABASE_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  bun:
    build:
      context: .
      dockerfile_inline: |
        FROM oven/bun:latest
        WORKDIR /app

        RUN apt-get update && apt-get install -y openssl ca-certificates libssl-dev postgresql-client

        COPY package.json bun.lock .
        RUN bun i

        COPY prisma ./prisma
        COPY prisma.config.ts ./

        COPY . .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_LOCATION: ${DATABASE_LOCATION}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_LOCATION}/${DATABASE_NAME}"
    entrypoint: >
        bash -c "
          echo 'Waiting for Postgres...';
          until PGPASSWORD=$POSTGRES_PASSWORD psql -h db -U $POSTGRES_USER -d $DATABASE_NAME -c \"\\q\"; do sleep 1; done;
          echo 'Postgres is ready, running migrations...';
          /app/node_modules/.bin/prisma generate;
          /app/node_modules/.bin/prisma migrate deploy;
          echo 'Starting Bun app...';
          bun run dev
        "



volumes:
  node_modules:
  next_cache:
